import ClubInvitations from '../app/club/club-invitations';
import ClubHeader from '../app/club/club-header';
/* eslint-disable @next/next/no-img-element -- Standalone local demo shares the original static brand artwork. */
import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import ClubActivity,{type ActivityView,type ClubApi} from '../app/club/club-activity';
function Preview(){
 const [signedOut,setSignedOut]=useState(()=>{try{return sessionStorage.getItem('ohpera-demo-signed-out')==='true';}catch{return false;}});
 function signOut(){try{sessionStorage.setItem('ohpera-demo-signed-out','true');}catch{}setSignedOut(true);setPlansCount(null);setView('calendar');}
 function resumePreview(){try{sessionStorage.removeItem('ohpera-demo-signed-out');}catch{}setSignedOut(false);}

 const [plansCount,setPlansCount]=useState<number|null>(null);
 const [sources,setSources]=useState<{id:string;name:string;url:string}[]>([]);
 useEffect(()=>{fetch('/coverage.json').then(r=>r.json()).then(data=>{if(data&&typeof data==='object'&&'sources' in data&&Array.isArray(data.sources))setSources(data.sources);}).catch(()=>{});},[]);
 const [member,setMember]=useState(2),[view,setView]=useState<ActivityView|'members'>('calendar');
 const api=useMemo<ClubApi>(()=>async<T,>(operation:string,payload:Record<string,unknown>={})=>{
  const response=await fetch('/rpc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({member,operation,payload})});
  const data:unknown=await response.json();if(!response.ok)throw new Error((data as {error?:string}).error||'Preview request failed.');return data as T;
 },[member]);
 if(signedOut)return <div className="club-app"><ClubHeader><img src="/images/oh-pera-singer-logo.png" className="club-demo-logo" width="260" height="100" alt="OH-pera!"/></ClubHeader><main className="club-main"><section className="club-page-heading"><p className="club-kicker">OH-pera local preview</p><h1>You’ve left the member preview.</h1><p>This demo uses fictional members. Your selected operas are kept while the preview server is running.</p><button onClick={resumePreview}>Return to member preview</button></section></main></div>;
 return <div className="club-app"><div className="club-demo-banner"><span><strong>LOCAL DEMO</strong> · Fictional members · Published schedule listings · Nothing is sent to real people.</span><label>Preview as<select value={member} onChange={e=>{setPlansCount(null);setMember(Number(e.target.value));}}><option value={2}>Maya (you)</option><option value={3}>Ahmet</option><option value={4}>Lina</option><option value={5}>Noah</option><option value={6}>Elena · other chain</option></select></label></div><ClubHeader><img src="/images/oh-pera-singer-logo.png" className="club-demo-logo" width="260" height="100" alt="OH-pera!"/><nav className="club-demo-nav" aria-label="Club navigation">{(['calendar','plans'] as ActivityView[]).map(item=><button key={item} aria-current={view===item?'page':undefined} onClick={()=>setView(item)}>{({calendar:'Calendar',plans:`My Plans${plansCount===null?'':` (${plansCount})`}`,messages:'Messages'})[item]}</button>)}<button aria-current={view==='members'?'page':undefined} onClick={()=>setView('members')}>Manage members</button><button onClick={signOut}>Sign out</button></nav></ClubHeader><main className="club-main">{view==='messages'&&<div className="club-demo-heading"><p className="club-kicker">Your private opera circle</p><h1>Make a plan together.</h1></div>}{view==='members'?<section className="club-members-page"><header className="club-calendar-welcome"><p className="club-kicker">Your private opera circle · New York</p><h1>Manage members</h1><p>Manage your invitees and welcome someone new.</p></header><ClubInvitations key={member} api={api} demo/></section>:<ClubActivity key={member} api={api} view={view} onView={setView} onPlansCount={setPlansCount}/>}{view==='calendar'&&<><p className="club-schedule-note">Browse all available listings in our NYC feed. Citywide coverage is incomplete; confirm dates and availability with the presenter. Attendance and messages in this preview are fictional.</p><details className="club-demo-help"><summary>Opera companies &amp; schedule coverage</summary><p>Some organizations publish announcements before individual dates. Check their official schedules for additional performances.</p><ul>{sources.map(source=><li key={source.id}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.name}</a></li>)}</ul></details><details className="club-demo-help"><summary>About this local demo</summary><p>Sofia → Maya → Ahmet → Lina → Noah. Elena belongs to a separate chain. Switch members above to explore visibility and private messages. Demo data resets when the server restarts.</p></details></>}</main></div>;
}
createRoot(document.getElementById('root')!).render(<Preview/>);
