'use client';
import {useCallback,useEffect,useState} from 'react';
import {FriendProfile,type ClubApi} from './club-activity';
import MemberConversation from './member-conversation';
type Invitation={id:string;email:string;expires_at:string;status:string;member:{id:string;display_name:string}|null};
type InvitationState={available:boolean;history:Invitation[];invitee:{id:string;display_name:string;status:string}|null};
export default function ClubInvitations({api,demo=false}:{api:ClubApi;demo?:boolean}){
 const [state,setState]=useState<InvitationState|null>(null),[email,setEmail]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirmRemove,setConfirmRemove]=useState(false),[confirmReplace,setConfirmReplace]=useState(false);
 const [memberAction,setMemberAction]=useState<'profile'|'chat'|null>(null);
 const load=useCallback(async()=>{setState(await api<InvitationState>('invitation_state'));},[api]);
 useEffect(()=>{let current=true;void api<InvitationState>('invitation_state').then(next=>{if(current)setState(next);}).catch(()=>{if(current)setError('Could not load your invitation. Please try again.');});return()=>{current=false;};},[api]);
 async function act(task:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 const current=state?.history.find(item=>item.status==='pending'||item.status==='accepted');
 return <div className="club-invitation-manager"><p>You can invite one person. Once they join, they can invite someone too.</p>{error&&<div role="alert"><p>{error}</p><button disabled={busy} onClick={()=>void act(load)}>Retry loading invitation</button></div>}{message&&<p role="status">{message}</p>}{!state&&!error&&<p role="status">Loading your invitation…</p>}

 <div className="club-member-management-grid"><section className="club-member-management-panel" aria-labelledby="my-invitees-heading"><h2 id="my-invitees-heading">My invitees</h2>
 {state?.available&&<p>You have no current invitees or pending invitations.</p>}
 {state?.invitee&&<ul className="club-invitee-list"><li className="club-invitation-current"><div className="club-invitee-row"><div><h3>{state.invitee.display_name}</h3><p>Your invitee · {state.invitee.status==='active'?'Joined the club':'Membership paused'}</p></div><details className="club-member-options"><summary>Options</summary><div><button onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');setMemberAction('profile');}}>View profile</button><button onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');setMemberAction('chat');}}>Start a chat</button><button onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');setConfirmRemove(true);}}>Remove member</button></div></details></div>{confirmRemove?<div className="club-remove-confirmation"><p>Remove {state.invitee.display_name} from the club? They will lose club access, and their pending invitation will be cancelled. People who already joined through them will keep their memberships.</p><div className="club-actions"><button disabled={busy} onClick={()=>void act(async()=>{await api('remove_invitee',{id:state.invitee!.id,confirmed:true});setConfirmRemove(false);await load();setMessage('Your invitee was removed. You can invite someone else.');})}>Confirm removal</button><button disabled={busy} onClick={()=>setConfirmRemove(false)}>Keep member</button></div></div>:null}</li></ul>}
 {current&&current.status==='pending'&&<ul className="club-invitee-list"><li className="club-invitation-current"><div className="club-invitee-row"><div><h3>{current.member?.display_name||current.email}</h3><p>Invitation pending</p></div><details className="club-member-options"><summary>Options</summary><div><button disabled={busy} onClick={()=>void act(async()=>{await api('revoke',{id:current.id});setLink('');await load();setMessage('Invitation cancelled. You can invite someone else.');})}>Cancel invitation</button></div></details></div>{current.status==='pending'&&<><p className="club-fine-print">Expires {new Date(current.expires_at).toLocaleDateString()}</p>{!link&&<div className="club-invitation-share">{confirmReplace?<><p>Create a replacement link for {current.email}? The previous link will stop working. No email is sent automatically.</p><div className="club-actions"><button disabled={busy} onClick={()=>void act(async()=>{await api('revoke',{id:current.id});setEmail(current.email);await load();const result=await api<{token:string}>('invite',{email:current.email}).catch(()=>{throw new Error('The previous link was cancelled, but the replacement could not be created. Your friend’s email is filled in below; choose Create invitation to try again.');});setLink(`${window.location.origin}/#invite=${result.token}`);setConfirmReplace(false);await load();setMessage('Replacement link created. Share this new link with your friend.');})}>Replace invitation link</button><button disabled={busy} onClick={()=>setConfirmReplace(false)}>Keep existing link</button></div></>:<button disabled={busy} onClick={()=>setConfirmReplace(true)}>Replace invitation link</button>}</div>}{link&&<div className="club-invitation-share"><label>Invitation link<input value={link} readOnly onFocus={event=>event.target.select()}/></label><button disabled={busy} onClick={()=>void act(async()=>{await navigator.clipboard.writeText(link);setMessage('Invitation link copied.');})}>Copy link</button>{!demo&&<a className="club-email-invitation" href={`mailto:${encodeURIComponent(current.email)}?subject=${encodeURIComponent('Your invitation to OH-pera')}&body=${encodeURIComponent(`Join my opera circle on OH-pera: ${link}\n\nThis invitation is for you and expires in seven days.`)}`}>Open email invitation</a>}</div>}</>}</li></ul>}
 {state&&!state.available&&!current&&!state.invitee&&<p>You have already invited a member.</p>}
 </section><section className="club-member-management-panel" aria-labelledby="new-invite-heading"><h2 id="new-invite-heading">Invite a new member</h2>
 {state&&!state.available&&<p className="club-invite-slot-note">{state.invitee?'Your invitation has been accepted. Each member can have one active invitee.':'Cancel your pending invitation before inviting someone new.'}</p>}
 <form onSubmit={event=>{event.preventDefault();void act(async()=>{const result=await api<{token:string}>('invite',{email:email.trim()});setLink(`${window.location.origin}/#invite=${result.token}`);await load();setMessage(demo?'Demo invitation created. No email has been sent.':'Invitation created. Share the link with your friend.');});}}><label>Invitee’s email<input disabled={!state?.available||busy} type="email" value={email} onChange={event=>setEmail(event.target.value)} required maxLength={254} autoComplete="off" placeholder="friend@example.com"/></label><p className="club-fine-print">Only this email address can accept. The invitation expires in seven days.</p><button className="club-primary" disabled={busy||!state?.available}>Create invitation</button></form>
 </section></div>
 {memberAction==='profile'&&state?.invitee&&<FriendProfile person={{...state.invitee,relationship:'Your invitee'}} api={api} onClose={()=>setMemberAction(null)} onMessage={()=>setMemberAction('chat')}/>}
 {memberAction==='chat'&&state?.invitee&&<MemberConversation person={state.invitee} api={api} onClose={()=>setMemberAction(null)}/>}
 {demo&&<p className="club-fine-print">Local demo only. Invitations are stored in this preview and no email is sent. Members who already invited someone have used their one invitation.</p>}
 </div>;
}
