'use client';
import HeroVideo from './hero-video';
import {operaIntroduction} from '../lib/opera-content';
import {useCallback,useEffect,useRef,useState} from 'react';
import {formatTime,isStale,nycDate,type Performance,type Schedule} from '../lib/schedule';
import {defaultFilters,displayTitle,filterEvents,normalize,type Filters} from '../lib/discovery';
const operaArtwork:Record<string,string> = {
 'macbeth':'macbeth','cosi fan tutte':'cosi-fan-tutte','la boheme':'la-boheme',
 'lincoln in the bardo':'lincoln-in-the-bardo','medea':'medea','samson et dalila':'samson-et-dalila',
 'la fanciulla del west':'la-fanciulla-del-west','silent night':'silent-night','manon':'manon','otello':'otello','parsifal':'parsifal'
};
const comingSoonArtwork:Record<string,string> = {
 'queeney todd the demon bottom of fleet street':'coming-soon-queeney-todd',
 'dvoraks rusalka':'coming-soon-rusalka',
 'verdis falstaff':'coming-soon-falstaff',
 'the tales of hoffmann':'coming-soon-tales-of-hoffmann',
 'the count of monte cristo':'coming-soon-count-of-monte-cristo'
};
function artworkFor(title:string){const key=title.split(' (')[0].normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();return operaArtwork[key];}
function comingSoonArtworkFor(title:string){return comingSoonArtwork[normalize(title).replace(/[^a-z0-9 ]/g,'')];}
const companyOptions = ['All companies','Metropolitan Opera','New York City Opera','Heartbeat Opera','Bronx Opera','BAM'];

function formatDate(date:string, long=false){ return new Intl.DateTimeFormat('en-US',long?{weekday:'long',month:'long',day:'numeric',year:'numeric'}:{month:'short',day:'numeric'}).format(new Date(`${date}T12:00:00`)); }

function Artwork({item,large=false}:{item:Performance;large?:boolean}){
  const artwork=artworkFor(item.title);
  return <div className={`art art-${item.palette} ${artwork?'art-illustrated':''} ${large?'art-large':''}`}>
    {artwork?<img src={`/images/operas/${artwork}.jpg`} alt={`Concept illustration inspired by ${item.title}`} loading={large?'eager':'lazy'} decoding="async" width={1536} height={1024}/>:<span className="art-title" aria-hidden="true">{item.title.slice(0,1)}</span>}
    <span className="art-mark">{item.label}</span>
  </div>;
}
function ComingSoonArtwork({title}:{title:string}){
  const artwork=comingSoonArtworkFor(title);
  if(!artwork)return null;
  return <div className="announcement-art"><img src={`/images/operas/${artwork}.jpg`} alt={`Concept illustration inspired by ${title}`} loading="lazy" decoding="async" fetchPriority="low" width={1536} height={1024}/></div>;
}

const kindName=(kind:string)=>kind==='screening'?'Cinema screening':kind==='concert'?'Opera concert':'Staged opera';
const dateNames:Record<string,string>={any:'Any date',week:'Next 7 days',weekend:'This weekend',month:'This month',date:'Choose a date'};
type View='discover'|'favorites'|'announcements'|'about';
function readLocation(){const p=new URLSearchParams(window.location.search);const f={...defaultFilters};for(const k of Object.keys(f) as (keyof Filters)[])f[k]=p.get(k)||f[k];if(!dateNames[f.range])f.range='any';if(!['all','opera','concert','screening'].includes(f.kind))f.kind='all';return {f,view:(['discover','favorites','announcements','about'].includes(p.get('view')||'')?p.get('view'):'discover') as View,event:p.get('event')||''};}
function Freshness({item}:{item:Performance}){return <p className={`verification-note ${isStale(item.checkedAt)||item.status!=='scheduled'?'needs-check':''}`}>{item.status==='cancelled'?'Cancelled':item.status==='unconfirmed'?'Needs reconfirmation':isStale(item.checkedAt)?'Older listing — confirm with presenter':item.verification==='manual'?'Manually sourced':'Source checked'}{item.verification==='secondary'?' · Secondary source':''}</p>;}
function ProductionDialog({item,onClose,saved,onSave}:{item:Performance;onClose:()=>void;saved:boolean;onSave:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current!;const opener=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden';return()=>{dialog.close();document.body.style.overflow=overflow;if(opener?.isConnected)opener.focus();else document.getElementById('results-heading')?.focus();};},[]);
 const title=displayTitle(item);
 const introduction=operaIntroduction(item);
 return <dialog ref={ref} className="production-dialog" aria-labelledby="detail-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}>
 <button className="close" autoFocus onClick={onClose} aria-label="Close performance details">×</button>
 <div className="dialog-layout"><div className="dialog-art"><Artwork item={item} large/></div><div className="dialog-copy">
 <p className="eyebrow">{item.company}</p><span className="event-kind">{kindName(item.kind)}</span><h2 id="detail-title">{title.title}</h2>{title.composer&&<p className="detail-composer">{title.composer}</p>}
 <dl className="production-facts"><div><dt>Date and time</dt><dd>{formatDate(item.date,true)}<br/>{formatTime(item.time)} · New York time</dd></div><div><dt>Venue</dt><dd>{item.venue||'Venue to be confirmed'}<br/>{[item.neighborhood,item.borough].filter(Boolean).join(', ')}</dd></div>{item.runtime&&<div><dt>Running time</dt><dd>{item.runtime}</dd></div>}{item.language&&<div><dt>Language</dt><dd>{item.language}</dd></div>}</dl>
 <section aria-label="About this opera"><h3>About this opera</h3><p className="synopsis">{introduction.text}</p><p className="check-date">{item.kind==='screening'?'This is a cinema screening, not an in-person stage performance.':item.kind==='concert'?'This is a concert presentation; staging varies by event.':'This listing is for a staged opera performance.'}</p>{introduction.source&&<a className="source-link" href={introduction.source} target="_blank" rel="noreferrer">Read more about the work</a>}</section><Freshness item={item}/><p className="check-date">{item.evidenceMethod==='indexed-official'?'Indexed official schedule reviewed':item.verification==='manual'?'Official page manually checked':item.verification==='secondary'?'Secondary source last checked':'Source last checked'} {new Date(item.checkedAt).toLocaleDateString('en-US',{timeZone:'America/New_York'})}. {item.verification==='manual'?`Review due ${item.reviewBy}. ${item.reviewedBy}.`:'This is a source-check date, not an independent editorial verification.'} Confirm details with the presenter.</p>
 <div className="detail-actions">{item.status!=='cancelled'&&<a className="ticket-button" href={item.ticketUrl||item.sourceUrl} target="_blank" rel="noreferrer">Check tickets</a>}<button className="outline-button" aria-pressed={saved} onClick={onSave}>{saved?'♥ Saved date':'♡ Save this date'}</button><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="source-link">Official presenter</a>{item.provenanceUrl&&<a href={item.provenanceUrl} target="_blank" rel="noreferrer" className="source-link">Listing data source</a>}</div>
 <p className="check-date">This performance has a shareable URL in your address bar.</p></div></div></dialog>;
}
export default function Home(){
 const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const sync=()=>setScrolled(window.scrollY>0);sync();window.addEventListener('scroll',sync,{passive:true});return()=>window.removeEventListener('scroll',sync);},[]);
 const [schedule,setSchedule]=useState<Schedule|null>(null),[error,setError]=useState(false),[today,setToday]=useState(nycDate());
 const [view,setView]=useState<View>('discover'),[f,setF]=useState<Filters>(defaultFilters),[eventId,setEventId]=useState(''),[ready,setReady]=useState(false);
 const [favorites,setFavorites]=useState<string[]>([]),[savedRecords,setSavedRecords]=useState<Record<string,Performance>>({}),[archive,setArchive]=useState(false),[refresh,setRefresh]=useState(0);
 // Initialize URL and browser-local saves after hydration, when browser APIs are available.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const sync=()=>{const state=readLocation();setF(state.f);setView(state.view);setEventId(state.event);};sync();try{const ids=JSON.parse(localStorage.getItem('ohpera-favorites')||'[]');if(Array.isArray(ids))setFavorites(ids.filter(x=>typeof x==='string'));const records=JSON.parse(localStorage.getItem('ohpera-saved-records')||'{}');if(records&&typeof records==='object'&&!Array.isArray(records))setSavedRecords(records);}catch{}setReady(true);window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 useEffect(()=>{if(!ready)return;const params=new URLSearchParams();if(view!=='discover')params.set('view',view);for(const k of Object.keys(f) as (keyof Filters)[])if(f[k]!==defaultFilters[k]&&f[k])params.set(k,f[k]);if(eventId)params.set('event',eventId);const query=params.toString();window.history.replaceState(window.history.state,'',window.location.pathname+(query?'?'+query:''));},[f,view,eventId,ready]);
 useEffect(()=>{const controller=new AbortController();const load=async()=>{try{const res=await fetch('/api/performances',{signal:controller.signal});if(!res.ok)throw Error();const data:Schedule=await res.json();if(!Array.isArray(data.performances)||!Array.isArray(data.sources)||!Array.isArray(data.announcements))throw Error();setSchedule(data);setError(false);setToday(nycDate());}catch{if(!controller.signal.aborted)setError(true);}};void load();const timer=setInterval(load,300000);return()=>{controller.abort();clearInterval(timer);};},[refresh]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('ohpera-favorites',JSON.stringify(favorites));localStorage.setItem('ohpera-saved-records',JSON.stringify(savedRecords));}catch{}},[favorites,savedRecords,ready]);
 // Keep archived save details synchronized with the latest external schedule snapshot.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!schedule||!favorites.length)return;setSavedRecords(old=>{const next={...old};for(const p of schedule.performances)if(favorites.includes(p.id))next[p.id]=p;return next;});},[schedule,favorites]);
 const events=schedule?.performances||[];const upcoming=events.filter(p=>p.date>=today);const savedUpcoming=upcoming.filter(p=>favorites.includes(p.id));const archived=favorites.filter(id=>!savedUpcoming.some(p=>p.id===id));
 const filtered=filterEvents(view==='favorites'?savedUpcoming:events,f,today).sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'99:99').localeCompare(b.time||'99:99'));
 const venues=[...new Set(events.map(p=>p.venue).filter((v):v is string=>!!v))].sort();
 const announced=(schedule?.announcements||[]).filter(a=>!['imaginative programs','dynamic concerts','open-air performance'].includes(normalize(a.title)));
 const announcements=announced.filter(a=>(f.company==='all'||a.company===f.company)&&normalize(a.title+' '+a.company).includes(normalize(f.q)));
 const selected=events.find(p=>p.id===eventId);
 const close=useCallback(()=>{if(window.history.state?.operaDetail)window.history.back();else setEventId('');},[]);
 const openEvent=(id:string)=>{window.history.pushState({operaDetail:true},'',window.location.href);setEventId(id);};
 const update=(key:keyof Filters,value:string)=>setF(old=>({...old,[key]:value}));
 const navigate=(next:View)=>{window.history.pushState({},'',window.location.href);setView(next);setF(defaultFilters);setEventId('');setArchive(false);window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 const toggleSave=(p:Performance)=>{setFavorites(old=>old.includes(p.id)?old.filter(id=>id!==p.id):[...old,p.id]);setSavedRecords(old=>({...old,[p.id]:p}));};
 const removeSaved=(id:string)=>{setFavorites(old=>old.filter(x=>x!==id));setSavedRecords(old=>{const next={...old};delete next[id];return next;});};
 const chips=(Object.keys(f) as (keyof Filters)[]).filter(k=>f[k]!==defaultFilters[k]&&f[k]&&k!=='date'&&(view!=='announcements'||['q','company'].includes(k)));
 const renderCard=(p:Performance)=>{const title=displayTitle(p);return <article className="performance-card production-card" key={p.id}><div className="card-performance-date"><time dateTime={p.date}>{formatDate(p.date,true)}</time><span>{formatTime(p.time)}</span></div><div className="art-wrap"><Artwork item={p}/><button className={`save ${favorites.includes(p.id)?'saved':''}`} aria-pressed={favorites.includes(p.id)} aria-label={`${favorites.includes(p.id)?'Unsave':'Save'} ${title.title}, ${formatDate(p.date,true)}`} onClick={()=>toggleSave(p)}>{favorites.includes(p.id)?'♥':'♡'}</button></div><div className="production-body"><p className="company">{p.company}</p><span className="event-kind">{kindName(p.kind)}</span><h3>{title.title}</h3>{title.composer&&<p className="composer">{title.composer}</p>}<p className="venue-line">{p.venue||p.borough} · {p.borough}</p><Freshness item={p}/><button className="details-button" onClick={()=>openEvent(p.id)} aria-label={`View ${title.title} on ${formatDate(p.date,true)}, ${p.company}`}>View performance</button></div></article>;};
 return <><a className="skip-link" href="#main-content">Skip to content</a><header className={`site-header ${scrolled?'is-scrolled':''}`}><button className="wordmark" onClick={()=>navigate('discover')} aria-label="OH-pera home">OH<span>—</span>pera!</button><nav aria-label="Primary navigation">{([['discover','Discover'],['favorites',`Saved (${savedUpcoming.length})`],['announcements','Coming Soon'],['about','About']] as [View,string][]).map(([key,label])=><button key={key} aria-current={view===key?'page':undefined} className={view===key?'active':''} onClick={()=>navigate(key)}>{label}</button>)}</nav><span className="header-location">New York City</span></header>
 <main id="main-content">{view==='about'?<About onDiscover={()=>navigate('discover')}/>:<>
 <section className={`hero ${view==='discover'?'illustrated-hero':'compact-hero'}`}>{view==='discover'&&<HeroVideo/>}<p className="eyebrow">{view==='discover'?'New York City · Find your next evening':view==='favorites'?'Your personal shortlist':'Looking ahead'}</p><h1>{view==='discover'?<>An opera for<br/><em>your evening.</em></>:view==='favorites'?'Your saved dates.':'Coming soon.'}</h1><p className="intro">{view==='discover'?'Explore the operas, choose a date, and make a night of it.':view==='favorites'?'Saved on this device. Pick a performance when you’re ready to go.':'Announced productions with individual dates still to be confirmed.'}</p>
 <div className="hero-search"><label className="field">Search {view==='announcements'?'announcements':'operas or composers'}<input type="search" placeholder="Try Macbeth or Mozart" value={f.q} onChange={e=>update('q',e.target.value)}/></label>{view!=='announcements'&&<label className="field">When<select value={f.range} onChange={e=>update('range',e.target.value)}>{Object.entries(dateNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}{view!=='announcements'&&f.range==='date'&&<label className="field">Date<input type="date" min={today} value={f.date} onChange={e=>update('date',e.target.value)}/></label>}</div>{view==='discover'&&<a className="hero-explore" href="#results-heading">Explore performances</a>}</section>
 <section className="discover" aria-labelledby="results-heading"><div className="section-head"><div><p className="section-kicker">{view==='favorites'?'Your shortlist':view==='announcements'?'Looking ahead':'Explore NYC opera'}</p><h2 id="results-heading" tabIndex={-1}>{view==='favorites'?'Saved performances':view==='announcements'?'Coming Soon':'Find your next opera'}</h2></div>{view==='discover'&&<button className="text-button" onClick={()=>navigate('announcements')}>Coming Soon ({announced.length}) ↗</button>}</div>
 {view==='favorites'&&<p className="check-date">Saved on this browser only. Clearing browser data removes your saves; they do not sync across devices.</p>}{view==='favorites'&&<div className="segmented" aria-label="Saved date category"><button aria-pressed={!archive} onClick={()=>setArchive(false)}>Upcoming ({savedUpcoming.length})</button><button aria-pressed={archive} onClick={()=>setArchive(true)}>Past / unavailable ({archived.length})</button></div>}
 {!(view==='favorites'&&archive)&&<>{view!=='announcements'&&<div className="date-shortcuts" aria-label="Quick date filters">{(['any','week','weekend','month'] as const).map(range=><button key={range} aria-pressed={f.range===range} onClick={()=>update('range',range)}>{dateNames[range]}</button>)}</div>}<div className="discovery-toolbar"><label className="field">Company<select value={f.company} onChange={e=>update('company',e.target.value)}><option value="all">All companies</option>{companyOptions.slice(1).map(c=><option key={c}>{c}</option>)}</select></label>{view!=='announcements'&&<><label className="field">Venue<select value={f.venue} onChange={e=>update('venue',e.target.value)}><option value="all">All venues</option>{[...new Set([...venues,...(f.venue!=='all'?[f.venue]:[])])].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Event type<select value={f.kind} onChange={e=>update('kind',e.target.value)}><option value="all">All event types</option><option value="opera">Staged opera</option><option value="concert">Opera concerts</option><option value="screening">Cinema screenings</option></select></label><label className="field">Borough<select value={f.borough} onChange={e=>update('borough',e.target.value)}><option value="all">All boroughs</option>{['Manhattan','Brooklyn','Queens','The Bronx','Staten Island'].map(b=><option key={b}>{b}</option>)}</select></label></>}</div>
 {!!chips.length&&<div className="filter-chips" aria-label="Active filters">{chips.map(k=><button key={k} onClick={()=>setF(old=>({...old,[k]:defaultFilters[k],...(k==='range'?{date:''}:{})}))}>Remove {k==='range'?(f.range==='date'?f.date||'Choose a date':dateNames[f.range]):k==='kind'?kindName(f.kind):f[k]} ×</button>)}<button className="text-button" onClick={()=>setF(defaultFilters)}>Clear all</button></div>}</>}
 <p className="results-summary" role="status">{!schedule?'Loading schedules…':view==='announcements'?`${announcements.length} announced productions · Dates are not confirmed` :view==='favorites'&&archive?`${archived.length} past or unavailable saved dates`:`${filtered.length} ${filtered.length===1?'performance':'performances'} · Times in New York`}</p>
 {schedule&&<p className="coverage-brief">{error?'Refresh unavailable. Showing previously loaded listings.':schedule.delivery==='bundled'?'Showing a saved schedule snapshot.':'Five organizations monitored; coverage is incomplete.'} Coverage is incomplete: gaps do not mean there are no performances. Some dates are manually sourced; check the presenter before planning. <a href="#source-coverage">View sources and coverage</a></p>}
 {!schedule?<div className="empty"><p>{error?'Schedules could not be loaded.':'Loading performances…'}</p>{error&&<button onClick={()=>setRefresh(n=>n+1)}>Try again</button>}</div>:view==='favorites'&&archive?<><p className="check-date">These dates have passed or are no longer present in the current feed. Missing does not mean cancelled. Search and outing filters do not apply here.</p>{archived.length?<ul className="archived-list">{archived.map(id=>{const p=savedRecords[id];return <li key={id}><div><strong>{p?.title?displayTitle(p).title:'Previously saved performance'}</strong><p>{p?.date?formatDate(p.date,true):'Details unavailable'}{p?.company?` · ${p.company}`:''}</p></div><button className="outline-button" onClick={()=>removeSaved(id)}>Remove saved date</button></li>;})}</ul>:<div className="empty"><h3>No archived dates</h3><p>Past and unavailable saved performances will appear here.</p></div>}</>:view==='announcements'?<><p className="check-date">Search and company filters apply here. Exact-date, venue, borough, and event-type filters apply only to scheduled performances.</p>{announcements.length?<div className="announcement-grid">{announcements.map(a=><article key={a.id}><ComingSoonArtwork title={a.title}/><div className="announcement-body"><p className="company">{a.company}</p><span className="event-kind">Season announcement</span><h3>{a.title}</h3><p>{a.dateText}</p><p className="check-date">{a.note}</p><a href={a.sourceUrl} target="_blank" rel="noreferrer">View announcement</a></div></article>)}</div>:<div className="empty"><h3>No matching announcements</h3><p>Try another company or search term.</p><button onClick={()=>setF(defaultFilters)}>Clear filters</button></div>}</>:filtered.length?<div className="performance-timeline" role="region" aria-label="Performances in date order" tabIndex={0}>{filtered.map(renderCard)}</div>:<div className="empty"><h3>{view==='favorites'&&!savedUpcoming.length?'No upcoming saved dates':f.range==='date'&&!f.date?'Choose a date above':'No matching performances'}</h3><p>{view==='favorites'&&!savedUpcoming.length?'Save a specific date from an opera card or its details. Saves stay in this browser on this device. Past or missing saved dates are available in the archive.':`Try another date or company.${f.company!=='all'?' Some companies only have season announcements available.':''}`}</p><button onClick={()=>view==='favorites'&&!savedUpcoming.length?navigate('discover'):setF(defaultFilters)}>{view==='favorites'&&!savedUpcoming.length?'Discover operas':'Clear filters'}</button>{view==='discover'&&<button className="outline-button" onClick={()=>navigate('announcements')}>View season announcements</button>}</div>}
 </section></>}
 <section id="source-coverage" className="coverage-section"><details className="coverage"><summary>Sources &amp; coverage {schedule&&`· ${schedule.sources.filter(s=>s.status!=='live'||isStale(s.lastSuccessAt)).length} need attention`}</summary><p>We monitor five organizations, not every NYC opera company. Older listings and secondary sources are labeled. Automated source checks and manually sourced listings are labeled separately. Manual listings have review deadlines; overdue entries need reconfirmation. Missing events are not assumed cancelled. All times use New York local time.</p><div className="source-grid">{schedule?.sources.map(s=><article key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a><strong>{s.status==='error'?'Update failed':s.status==='fallback'?'Secondary snapshot':s.status==='partial'?'Partial coverage':'Connected'}{isStale(s.lastSuccessAt)?' · Out of date':''}</strong><p>{s.message}</p><small>{s.lastSuccessAt?`Source checked ${new Date(s.lastSuccessAt).toLocaleString('en-US',{timeZone:'America/New_York'})} ET`:'No successful source check'}</small></article>)}</div></details></section>
 </main><footer><div className="wordmark">OH<span>—</span>pera!</div><p>Find your next evening.</p><p className="footer-note">Confirm availability with the presenter before booking. Opera illustrations are AI-generated and do not depict actual productions.</p><p id="film-credit" className="film-credit">Hero video: Maria Callas performs “Vissi d’arte” from Puccini’s <em>Tosca</em> on <a href="https://www.edsullivan.com/artists/maria-callas/" target="_blank" rel="noreferrer">The Ed Sullivan Show, New York, November 25, 1956</a>. Embedded from The Ed Sullivan Show’s official YouTube channel. Archival footage; not a current performance listing.</p></footer>
 {selected&&<ProductionDialog item={selected} onClose={close} saved={favorites.includes(selected.id)} onSave={()=>toggleSave(selected)}/>}
 {!!eventId&&schedule&&!selected&&<div className="unavailable-link" role="status">This shared performance is no longer available in the current schedule. <button onClick={close}>Dismiss</button></div>}
 </>;
}
function About({onDiscover}:{onDiscover:()=>void}){return <section className="about-page"><div><p className="eyebrow">About OH-pera!</p><h1>One city.<br/>Many stages.<br/>More discovery.</h1></div><div className="about-copy"><p className="about-lead">Opera in New York shouldn’t require five tabs and a perfect memory.</p><p>OH-pera! monitors the Metropolitan Opera, New York City Opera, Heartbeat Opera, Bronx Opera, and opera presented at BAM. Coverage is expanding. Some sources provide season announcements or older snapshots rather than current individual dates; each listing shows its verification status.</p><p>We don’t sell tickets. When you find something you love, we send you directly to the presenter’s official website.</p><button onClick={onDiscover}>Discover what’s on</button><div className="company-list">{companyOptions.slice(1).map((name,index)=><div key={name}><span>0{index+1}</span>{name}</div>)}</div></div></section>}
